### ISSUE TITLE
App crashes on clicking HQ option after surfing help page

### ISSUE THREAD

**Issue by neupanedipen** [dozingcat/VectorCamera#14]
#### Expected behavior<br>
The app must be stable and should enable and disable the HQ feature.<br>
#### Actual behavior<br>
But the app crashes when I click on the HQ option once or twice after surfing the help page.<br>
#### How to reproduce<br>
1. Install the app from Fdroid.<br>
2. Launch the app.<br>
3. Click on the ? icon on top left corner of the app and surf the whole page once or twice.<br>
And go back to the overview page after surfing.<br>
4. Now click on the HQ option once or twice.<br>
The app crashes.<br>
* App Version: 1.2.2<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/N6qUJYCkgOI

**Comment by dozingcat** [comment]
Hopefully fixed in version 1.4.3 (via https://github.com/dozingcat/VectorCamera/pull/36).
