### ISSUE TITLE
App crashes on rotating camera after changing the effect

### ISSUE THREAD

**Issue by neupanedipen** [dozingcat/VectorCamera#15]
#### Expected behavior<br>
The app must be stable on choosing the effect and rotating the camera.<br>
#### Actual behavior<br>
But the app crashes when I try to change the effect and rotate the camera.<br>
#### How to reproduce<br>
1. Install the app from playstore.<br>
2. Launch the app.<br>
3. Click on settings icon and enable both the options of preferences.<br>![](https://s7.postimg.cc/79raxxu97/Screenshot_20180519-214259.png)
4. Now click on Effect option and select an effect.<br>![](https://s7.postimg.cc/kdwvam6vf/20180519_215751.png)
5. Now rotate the camera of the app.<br>![](https://s19.postimg.cc/ghz64c36b/20180519_215934.png)
The app usually crash after this step. If it didn&apos;t then try clicking on effect option again.<br>
The app crashes.<br>
* App Version: 1.2.2<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/1AkOcyDIeNE

**Comment by dozingcat** [comment]
Hopefully fixed in version 1.4.3 (via https://github.com/dozingcat/VectorCamera/pull/36).
