### ISSUE TITLE
Application keeps crashing when HQ is activate and deactivate

### ISSUE THREAD

**Issue by adisalat2** [dozingcat/VectorCamera#19]
Project Information
-Repository
https://github.com/dozingcat/VectorCamera
-Project Name: Vector Camera

Expected Behaviour
The application should remain stable and not to crash when High Quality (HQ) is activated and deactivated.

Actual Behaviour
The application crashed immediately after High Quality (HQ) is activated and deactivated

How to reproduce
Download the app from playstore
Start the app
Click on HQ to activate,
Then click on it again to deactivate
Hence,the app crash

-Browser: Vector Camera v 1.2.3
-Operating System: Android 7.0

Recording of the bug
https://youtu.be/lJVLwxecKps

**Comment by dozingcat** [comment]
Hopefully fixed in version 1.4.3 (via https://github.com/dozingcat/VectorCamera/pull/36).
