### ISSUE TITLE
Application crashed when HQ is click several time

### ISSUE THREAD

**Issue by adisalat2** [dozingcat/VectorCamera#20]
Project Information
-Repository
https://github.com/dozingcat/VectorCamera
-Project Name: Vector Camera

Expected Behaviour
The application should remain stable and not to crash when High Quality (HQ) is clicked multiple times

Actual Behaviour
The application crashed immediately after clicking on HQ multiple times

How to reproduce
Download the app from playstore
Start the app
Click on HQ multiple times
Hence,the app crash

-Browser: Vector Camera v 1.2.3
-Operating System: Android 7.0

Recording of the bug
https://youtu.be/FY_Kyh_HB4U

**Comment by dozingcat** [comment]
Hopefully fixed in version 1.4.3 (via https://github.com/dozingcat/VectorCamera/pull/36).
