### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [dozingcat/VectorCamera#33]
Expected behavior:
I click at the app icon and the app opens.

Actual behavior:
The app crashes and doesn't start.

Steps to reproduce:
- download and install Vector Camera 1.4.2 from FDroid, Android 9, no GApps
- click at the app icon
- the app doesn't open
- click at the icon again
- Android shows a message that the app have crashed again.

**Comment by java-py-c-cpp-js** [comment]
Same with version 1.4.3

**Comment by Dr-Flay** [comment]
Install the google play version and it works

**Comment by dozingcat** [comment]
This is hopefully fixed in later versions, reopen if it's still occurring.
