### ISSUE TITLE
Save video

### ISSUE THREAD

**Issue by yephny** [dozingcat/VectorCamera#54]
It'd be great if there was a way to save a video recorded by VectorCamera. I tried sharing the video with [SaveTo...](https://www.f-droid.org/packages/xyz.myachin.saveto/) but it resulted in an empty file, so I have to send it to [Video Transcoder](https://www.f-droid.org/packages/protect.videoeditor/) first, then encode it in a different format to save it.

**Comment by dozingcat** [comment]
Not sure why SaveTo wouldn't work, I'll look into that. But you should be able to get to the WebM video files at `Android/data/com.dozingcatsoftware.vectorcamera/files/VectorCamera/VectorCamera_videos`.

**Comment by yephny** [comment]
Thanks, I'll use VectorCamera's directory.

**Comment by yephny** [comment]
@dozingcat Is it possible to extract the video in higher quality? I have an important video taken using VectorCamera but the webm export is extremely bad quality.

**Comment by yephny** [comment]
I extracted it as still frames, then merged them into a video.

**Comment by yephny** [comment]
Any updates on this one?

**Comment by lmj0011** [comment]
I would suggest allowing the the user to select the directory where they would like their images to be stored, or at the very least putting the media files into Shared Storage and not App-specific storage

ref: https://developer.android.com/training/data-storage

`Android/data/com.dozingcatsoftware.vectorcamera/files/VectorCamera` is not accessible for some reason in the Google Files app (Android 13)
