### ISSUE TITLE
Effect icon causes app to forcefully close down

### ISSUE THREAD

**Issue by blackmaryline** [dozingcat/VectorCamera#9]
#### Expected behavior
The effect icon should work perfectly as possible as many times been used.

#### Actual behavior
After downloading, I tapped the effect icon which is the second icon on the list, the app misbehaves after the second trial using the effect icon. It forces close down/stops working

#### How to reproduce
+ Download Vector camera
+ Open and use the effect icon which is the second icon on the list, the app will close down after more than a trial or two

* Browser: Vector camera (version 1.2.1) latest version on playstore 
* Operating system: Android Nougat 7.0

#### Recording Of The Bug
https://youtu.be/85tw8sq7c3s

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@timmyeu/effect-icon-causes-app-to-forcefully-close-down">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by dozingcat** [comment]
Is version 1.2.2 better for you?

**Comment by blackmaryline** [comment]
I'll check it out

On May 4, 2018 3:52 AM, "Brian Nenninger" <notifications@github.com> wrote:

Is version 1.2.2 better for you?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dozingcat/VectorCamera/issues/9#issuecomment-386494198>,
or mute the thread

**Comment by dozingcat** [comment]
Hopefully fixed in version 1.4.3 (via https://github.com/dozingcat/VectorCamera/pull/36).
